# Generated by Django 5.2.11 on 2026-02-20 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='magazine/{id}/', verbose_name='Cover Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='magazine/{id}/pdf/', verbose_name='PDF')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Issued At')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Page Count')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazine',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Visit',
                'verbose_name_plural': 'Site Visit',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('page_number', models.IntegerField(verbose_name='Page Number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='magazine/{magazine_id}/content/', verbose_name='Content Image')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True, verbose_name='Content Slug')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='magazine.magazine', verbose_name='Magazine')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['page_number'],
            },
        ),
    ]
