# Generated by Django 5.2.11 on 2026-02-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_content_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='view_count',
        ),
        migrations.AddField(
            model_name='content',
            name='c_pdf',
            field=models.FileField(blank=True, null=True, upload_to='magazine/{magazine_id}/content/pdf/', verbose_name='Content PDF'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
