# Generated by Django 5.2.11 on 2026-02-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_remove_content_view_count_content_c_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
