# Generated by Django 5.2.11 on 2026-02-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_magazine_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page Number'),
        ),
    ]
