# Generated by Django 5.2.11 on 2026-02-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_alter_content_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page_number',
            field=models.IntegerField(verbose_name='Page Number'),
        ),
    ]
